## Math and geometry utilities for Robocode Tank Royale bot API.
##
## This module provides helper functions for common calculations needed when
## writing a bot: angle normalization, bearing/distance calculations, and
## physics-related speed/distance computations.
##
## All angles in this API are in **degrees**, not radians.
##
## ## Angle Normalization
##
## - `normalizeRelativeAngle` -- Normalize to [-180, 180) range (signed turn)
## - `normalizeAbsoluteAngle` -- Normalize to [0, 360) range (absolute heading)
## - `calcDeltaAngle` -- Difference between two angles, normalized to [-180, 180)
##
## ## Geometry Helpers
##
## - `directionTo` -- Absolute angle from point A to point B
## - `distanceTo` -- Euclidean distance between two points
## - `bearingTo` -- Relative angle from current heading to target point
##
## ## Physics Helpers
##
## - `calcMaxTurnRate` -- Max body turn rate at a given speed
## - `calcBulletSpeed` -- Bullet velocity from firepower
## - `calcGunHeat` -- Gun heat generated by firing
## - `getMaxSpeed` -- Maximum speed to cover a distance
## - `getNewTargetSpeed` -- Next tick's speed for a given distance
## - `getDistanceTraveledUntilStop` -- Distance to coast to a stop
##
## ## See Also
##
## - `bot.calcBearing` -- Bearing to absolute angle (uses `calcDeltaAngle`)
## - `bot.bearingTo` -- Bearing to point (uses `utils.bearingTo`)
## - `bot.distanceTo` -- Distance to point (uses `utils.distanceTo`)
## - `constants.MAX_SPEED`, `MAX_TURN_RATE`, etc.

import std/math
import ./constants

proc isNearZero*(value: float): bool {.inline.} =
  ## Check if a float value is effectively zero (within 0.00001).
  ##
  ## Used internally for comparing floating-point values that should be zero
  ## but may have tiny rounding errors.
  abs(value) < 0.00001

proc normalizeRelativeAngle*(angle: float): float =
  ## Normalize an angle to the [-180, 180) range.
  ##
  ## This represents a **relative** (signed) angle -- positive means clockwise,
  ## negative means counter-clockwise. Use this for turn amounts.
  ##
  ## Example:
  ## ```nim
  ## normalizeRelativeAngle(270)   # -90.0 (shorter to turn left)
  ## normalizeRelativeAngle(-270)  # 90.0  (shorter to turn right)
  ## normalizeRelativeAngle(45)    # 45.0
  ## ```
  result = angle mod 360.0
  if result >= 180.0:
    result -= 360.0
  elif result < -180.0:
    result += 360.0

proc normalizeAbsoluteAngle*(angle: float): float {.inline.} =
  ## Normalize an angle to the [0, 360) range.
  ##
  ## This represents an **absolute** heading -- 0 = North, 90 = East,
  ## 180 = South, 270 = West. Use this for bot direction, gun direction, etc.
  ##
  ## Example:
  ## ```nim
  ## normalizeAbsoluteAngle(450)   # 90.0
  ## normalizeAbsoluteAngle(-90)   # 270.0
  ## normalizeAbsoluteAngle(180)   # 180.0
  ## ```
  (angle mod 360.0 + 360.0) mod 360.0

proc calcDeltaAngle*(targetAngle, sourceAngle: float): float {.inline.} =
  ## Calculate the shortest signed turn from `sourceAngle` to `targetAngle`.
  ##
  ## Returns a value in [-180, 180). Positive = turn right, negative = turn left.
  ## This is the core function for all turning calculations.
  ##
  ## Example:
  ## ```nim
  ## calcDeltaAngle(90, 0)    # 90.0  (turn right 90°)
  ## calcDeltaAngle(0, 90)    # -90.0 (turn left 90°)
  ## calcDeltaAngle(10, 350)  # 20.0  (turn right 20°, not left 340°)
  ## ```
  normalizeRelativeAngle(targetAngle - sourceAngle)

proc calcMaxTurnRate*(speed: float): float {.inline.} =
  ## Calculate the maximum body turn rate at a given speed.
  ##
  ## The faster you move, the slower you can turn. At max speed (8.0),
  ## the max turn rate is reduced to 4.0°/tick.
  ##
  ## Formula: `MAX_TURN_RATE - 0.75 * |speed|`
  ##
  ## Parameters:
  ## - `speed`: Current speed (clamped between `-MAX_SPEED` and `MAX_SPEED`)
  ##
  ## Returns: Maximum turn rate in degrees per tick
  MAX_TURN_RATE - 0.75 * abs(speed.clamp(-MAX_SPEED, MAX_SPEED))

proc calcBulletSpeed*(firepower: float): float {.inline.} =
  ## Calculate bullet velocity from firepower.
  ##
  ## Higher firepower = slower bullet but more damage.
  ## Formula: `20.0 - 3.0 * firepower`
  ##
  ## Parameters:
  ## - `firepower`: Bullet power (clamped between 0.1 and 3.0)
  ##
  ## Returns: Bullet speed in units per tick
  ##
  ## Example:
  ## ```nim
  ## calcBulletSpeed(0.1)  # 19.7 (fast, weak)
  ## calcBulletSpeed(1.0)  # 17.0
  ## calcBulletSpeed(3.0)  # 11.0 (slow, powerful)
  ## ```
  20.0 - 3.0 * firepower.clamp(MIN_FIRE_POWER, MAX_FIRE_POWER)

proc calcGunHeat*(firepower: float): float {.inline.} =
  ## Calculate gun heat generated by firing.
  ##
  ## You cannot fire again until gun heat cools to 0.
  ## Cooling rate is determined by `GameSetup.gunCoolingRate` (default 0.1/tick).
  ## Formula: `1.0 + firepower / 5.0`
  ##
  ## Parameters:
  ## - `firepower`: Bullet power (clamped between 0.1 and 3.0)
  ##
  ## Returns: Gun heat generated
  ##
  ## Example:
  ## ```nim
  ## calcGunHeat(0.1)  # 1.02
  ## calcGunHeat(1.0)  # 1.2
  ## calcGunHeat(3.0)  # 1.6
  ## ```
  1.0 + firepower.clamp(MIN_FIRE_POWER, MAX_FIRE_POWER) / 5.0

proc directionTo*(fromX, fromY, toX, toY: float): float {.inline.} =
  ## Calculate absolute angle from point A to point B.
  ##
  ## Returns angle in [0, 360) where 0 = North, 90 = East.
  ##
  ## Parameters:
  ## - `fromX`, `fromY`: Starting position
  ## - `toX`, `toY`: Target position
  ##
  ## Returns: Absolute angle in degrees
  ##
  ## Example:
  ## ```nim
  ## directionTo(0, 0, 100, 0)   # 90.0  (East)
  ## directionTo(0, 0, 0, 100)   # 0.0   (North)
  ## directionTo(0, 0, -100, 0)  # 270.0 (West)
  ## ```
  normalizeAbsoluteAngle(180.0 * arctan2(toY - fromY, toX - fromX) / PI)

proc distanceTo*(fromX, fromY, toX, toY: float): float {.inline.} =
  ## Calculate Euclidean distance between two points.
  ##
  ## Parameters:
  ## - `fromX`, `fromY`: Starting position
  ## - `toX`, `toY`: Target position
  ##
  ## Returns: Distance in game units
  ##
  ## Example:
  ## ```nim
  ## distanceTo(0, 0, 3, 4)  # 5.0
  ## ```
  let dx = toX - fromX
  let dy = toY - fromY
  sqrt(dx * dx + dy * dy)

proc bearingTo*(fromX, fromY, fromDir, toX, toY: float): float {.inline.} =
  ## Calculate relative bearing from current heading to target point.
  ##
  ## This is the angle you need to turn to face the target.
  ## Returns value in [-180, 180). Positive = turn right, negative = turn left.
  ##
  ## Parameters:
  ## - `fromX`, `fromY`: Your position
  ## - `fromDir`: Your current heading (absolute angle)
  ## - `toX`, `toY`: Target position
  ##
  ## Returns: Relative bearing in degrees
  ##
  ## Example:
  ## ```nim
  ## # Facing North (0), target at East (100, 0)
  ## bearingTo(0, 0, 0, 100, 0)  # 90.0  (turn right 90°)
  ## 
  ## # Facing East (90), target at North (0, 100)
  ## bearingTo(0, 0, 90, 0, 100) # -90.0 (turn left 90°)
  ## ```
  normalizeRelativeAngle(directionTo(fromX, fromY, toX, toY) - fromDir)

# ---- Speed / distance helpers -----------------------------------------------

proc getMaxDeceleration(speed: float): float =
  let decelerationTime = speed / ABS_DECELERATION
  let accelerationTime = 1.0 - decelerationTime
  min(1.0, decelerationTime) * ABS_DECELERATION + max(0.0, accelerationTime) * ACCELERATION

proc getMaxSpeed(distance: float): float =
  let decelerationTime = max(1.0, ceil((sqrt(4.0 * 2.0 / ABS_DECELERATION * distance + 1.0) - 1.0) / 2.0))
  if decelerationTime == Inf: return MAX_SPEED
  let decelerationDistance = (decelerationTime / 2.0) * (decelerationTime - 1.0) * ABS_DECELERATION
  ((decelerationTime - 1.0) * ABS_DECELERATION) + ((distance - decelerationDistance) / decelerationTime)

proc getNewTargetSpeed*(maxSpeed, speed, distance: float): float =
  if distance < 0.0:
    return -getNewTargetSpeed(maxSpeed, -speed, -distance)
  let targetSpeed =
    if distance == Inf: maxSpeed
    else: min(maxSpeed, getMaxSpeed(distance))
  if speed >= 0.0:
    targetSpeed.clamp(speed - ABS_DECELERATION, speed + ACCELERATION)
  else:
    targetSpeed.clamp(speed - ACCELERATION, speed + getMaxDeceleration(-speed))

proc getDistanceTraveledUntilStop*(maxSpeed, speed: float): float =
  var s = abs(speed)
  var dist = 0.0
  while s > 0.0:
    s = getNewTargetSpeed(maxSpeed, s, 0.0)
    dist += s
  dist
